=== jnphilipp/backup/backup.xsd
<?xml version="1.0"?>
<xs:schema targetNamespace="https://github.com/jnphilipp/backup/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:p="https://github.com/jnphilipp/backup/" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="backup" type="p:backupType">
        <xs:unique name="UniqueOptionName">
            <xs:selector xpath=".//option"/>
            <xs:field xpath="@name"/>
        </xs:unique>
        <xs:unique name="UniqueStepNo">
            <xs:selector xpath=".//step"/>
            <xs:field xpath="@no"/>
        </xs:unique>
        <xs:unique name="UniqueScriptId">
            <xs:selector xpath=".//script"/>
            <xs:field xpath="@id"/>
        </xs:unique>
        <xs:unique name="UniqueSourcePath">
            <xs:selector xpath=".//source/path"/>
            <xs:field xpath="."/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="backupType">
        <xs:sequence>
            <xs:element name="options" type="p:optionsType" minOccurs="0"/>
            <xs:element name="scripts" type="p:scriptsType" minOccurs="0"/>
            <xs:element name="sources" type="p:sourcesType" minOccurs="0"/>
            <xs:element name="databases" type="p:databasesType" minOccurs="0"/>
            <xs:element name="pipeline" type="p:pipelineType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="optionsType">
        <xs:sequence>
            <xs:element name="rsync" type="p:rootStrType" minOccurs="0"/>
            <xs:element name="target" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="rootStrType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="root" type="p:BooleanType" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="BooleanType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="1"/>
            <xs:enumeration value="yes"/>
            <xs:enumeration value="true"/>
            <xs:enumeration value="on"/>
            <xs:enumeration value="0"/>
            <xs:enumeration value="no"/>
            <xs:enumeration value="false"/>
            <xs:enumeration value="off"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="pipelineType">
        <xs:sequence>
            <xs:element name="step" type="p:stepType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="stepType">
        <xs:simpleContent>
            <xs:extension base="p:stepValueType">
                <xs:attribute name="no" type="xs:integer" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="stepValueType">
        <xs:restriction base="xs:string">
            <xs:pattern value="backup|mysql-dbs|postgresql-dbs|script-[0-9]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="scriptsType">
        <xs:sequence>
            <xs:element name="script" type="p:scriptType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="scriptType">
        <xs:sequence>
            <xs:element name="command" type="xs:string"/>
            <xs:element name="args" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:integer" use="required"/>
        <xs:attribute name="root" type="p:BooleanType" use="optional"/>
    </xs:complexType>

    <xs:complexType name="sourcesType">
        <xs:sequence>
            <xs:element name="file" type="p:rootStrType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="source" type="p:sourceType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="sourceType">
        <xs:sequence>
            <xs:element name="path" type="p:pathType"/>
            <xs:element name="exclude" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="target" type="xs:string" minOccurs="0"/>
            <xs:element name="rsync" type="p:rootStrType" minOccurs="0"/>
            <xs:element name="pre_script" type="xs:integer" minOccurs="0"/>
            <xs:element name="post_script" type="xs:integer" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="pathType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="host" type="xs:string" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="databasesType">
        <xs:sequence>
            <xs:element name="file" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="postgresql" type="p:dbsType" minOccurs="0"/>
            <xs:element name="mysql" type="p:dbsType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dbsType">
        <xs:sequence>
            <xs:element name="db" type="p:dbType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dbType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="user" type="xs:string"/>
            <xs:element name="password" type="xs:string" minOccurs="0"/>
            <xs:element name="pass" type="xs:string" minOccurs="0"/>
            <xs:element name="options" type="xs:string" minOccurs="0"/>
            <xs:element name="ssh" type="xs:string" minOccurs="0"/>
            <xs:element name="target" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== jnphilipp/backup/tests/tar.xml
<?xml version="1.0" encoding="UTF-8"?>
<backup xmlns="https://github.com/jnphilipp/backup/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/jnphilipp/backup/ https://raw.githubusercontent.com/jnphilipp/backup/master/backup.xsd">
    <tool name="tar">--create --gzip --listed-incremental=%s --verbose</tool>
    <sources>
        <file>data.xml</file>
        <source><path>/boot</path></source>
        <source><path>/etc</path></source>
        <source>
            <path>/root</path>
            <exclude>**/.cache</exclude>
            <exclude>**/.dbus</exclude>
            <exclude>**/.gvfs</exclude>
        </source>
        <source>
            <path>/var/</path>
            <exclude>/crash</exclude>
            <exclude>/tmp</exclude>
            <exclude>/log</exclude>
            <exclude>/spool</exclude>
        </source>
        <source>
            <path>/srv/</path>
            <exclude>**/venv</exclude>
            <exclude>**/.venv</exclude>
            <exclude>**/__pycache__</exclude>
            <exclude>**/.mypy_cache</exclude>
        </source>
    </sources>
    <pipeline>
        <step no="1">backup</step>
    </pipeline>
</backup>

=== jnphilipp/backup/tests/borg2.xml
<?xml version="1.0" encoding="UTF-8"?>
<backup xmlns="https://github.com/jnphilipp/backup/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/jnphilipp/backup/ https://raw.githubusercontent.com/jnphilipp/backup/master/backup.xsd">
    <tool name="borg">--verbose --list --stats --show-rc --compression zstd,11 --exclude-caches</tool>
    <sources>
        <source><path>/boot</path></source>
        <source><path>/etc</path></source>
        <source>
            <path>/home</path>
            <exclude>*.pyc</exclude>
            <exclude>**/.cache</exclude>
            <exclude>**/venv</exclude>
            <exclude>**/.venv</exclude>
            <exclude>**/__pycache__</exclude>
            <exclude>**/.mypy_cache</exclude>
        </source>
        <source><path>/opt</path></source>
        <source><path>/root</path></source>
        <source><path>/srv</path></source>
        <source>
            <path>/var</path>
            <exclude>var/**/logs</exclude>
            <exclude>pp:var/cache</exclude>
            <exclude>pp:var/crash</exclude>
            <exclude>pp:var/log</exclude>
            <exclude>pp:var/lock</exclude>
            <exclude>pp:var/run</exclude>
            <exclude>pp:var/spool</exclude>
            <exclude>pp:var/tmp</exclude>
            <pattern>+var/cache/pacman</pattern>
        </source>
    </sources>
    <pipeline>
        <step no="1">backup</step>
    </pipeline>
</backup>

=== jnphilipp/backup/tests/rsync2.xml
<?xml version="1.0" encoding="UTF-8"?>
<backup xmlns="https://github.com/jnphilipp/backup/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/jnphilipp/backup/ https://raw.githubusercontent.com/jnphilipp/backup/master/backup.xsd">
    <tool name="rsync">--delete --delete-excluded --stats --backup-dir=%s -abuchvz</tool>
    <target>/mnt/BACKUPS</target>
    <sources>
        <source>
            <path>/</path>
            <exclude>*.pyc</exclude>
            <exclude>**/.cache</exclude>
            <exclude>**/venv</exclude>
            <exclude>**/.venv</exclude>
            <exclude>**/__pycache__</exclude>
            <exclude>**/.mypy_cache</exclude>
            <exclude>**/.local/share/Trash</exclude>
            <include>/boot/***</include>
            <include>/etc/***</include>
            <exclude>/home</exclude>
            <exclude>/opt</exclude>
            <exclude>/proc</exclude>
            <include>/root/***</include>
            <exclude>/run</exclude>
            <include>/srv/***</include>
            <exclude>/tmp</exclude>
            <exclude>/var/**/logs</exclude>
            <exclude>/var/cache</exclude>
            <exclude>/var/crash</exclude>
            <exclude>/var/log</exclude>
            <exclude>/var/lock</exclude>
            <exclude>/var/run</exclude>
            <exclude>/var/spool</exclude>
            <exclude>/var/tmp</exclude>
            <include>/var/***</include>
            <include>/var/cache/pacman/***</include>
            <exclude>*</exclude>
        </source>
    </sources>
    <pipeline>
        <step no="1">backup</step>
    </pipeline>
</backup>

=== jnphilipp/backup/tests/scripts.xml
<?xml version="1.0" encoding="UTF-8"?>
<backup xmlns="https://github.com/jnphilipp/backup/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/jnphilipp/backup/ https://raw.githubusercontent.com/jnphilipp/backup/master/backup.xsd">
    <tool name="rsync">--delete --delete-excluded --stats --backup-dir=%s -abuchvz</tool>
    <target>/mnt/BACKUPS</target>
    <scripts>
        <script id="1">systemctl stop postgresql.service</script>
        <script id="2">systemctl start postgresql.service</script>
        <script id="3">echo "Hello World"</script>
        <script id="4">echo "Goodbye!"</script>
    </scripts>
    <sources>
        <source>
            <path>/</path>
            <exclude>*.pyc</exclude>
            <exclude>**/.cache</exclude>
            <exclude>**/venv</exclude>
            <exclude>**/.venv</exclude>
            <exclude>**/__pycache__</exclude>
            <exclude>**/.mypy_cache</exclude>
            <exclude>**/.local/share/Trash</exclude>
            <include>/boot/***</include>
            <include>/etc/***</include>
            <exclude>/home</exclude>
            <exclude>/opt</exclude>
            <exclude>/proc</exclude>
            <include>/root/***</include>
            <exclude>/run</exclude>
            <include>/srv/***</include>
            <exclude>/tmp</exclude>
            <exclude>/var/**/logs</exclude>
            <exclude>/var/cache</exclude>
            <exclude>/var/crash</exclude>
            <exclude>/var/log</exclude>
            <exclude>/var/lock</exclude>
            <exclude>/var/run</exclude>
            <exclude>/var/spool</exclude>
            <exclude>/var/tmp</exclude>
            <include>/var/***</include>
            <include>/var/cache/pacman/***</include>
            <exclude>*</exclude>
            <pre_script>1</pre_script>
            <post_script>2</post_script>
        </source>
    </sources>
    <pipeline>
        <step no="1">script-3</step>
        <step no="2">backup</step>
        <step no="3">script-4</step>
    </pipeline>
</backup>
